### Installation

If you have installed Anaconda, then you should be ready to go. If not, then you will have to install add-ons manually after installing Python, in the order of Numpy and the Scipy. You can use pip installer. Execute the following command to install:

 pip install numpy

Otherwise, if you are running Python via the Anaconda distribution, you can execute the following command instead:

conda install numpy

### Importing the Numpy module
There are several ways to import Numpy. The standard approach is to use a simple import setatement: 

In [1]:
#import numpy

However, for large amounts of calls to NumPy functions, it can become tedious to write numpy.X over and over again. Instead, it is common to import under the briefer name np:

In [2]:
import numpy as np

Above code renames the Numpy namespace to np. This permits us to prefix Numpy function, methods, and attributes with " np " instead of typing " numpy."
This statement will allow us to access NumPy objects using np.X instead of numpy.X. 

To check the version of numpy use the command

In [3]:
print (np.__version__)

1.26.2


### Arrays

The whole NumPy library is based on one main object: **ndarray** which stands for N-Dimensional array which is fast, flexible container for large datasets in Python. This object is a multidimensional homogeneous array with a predetermined number of items: homogeneous because virtually all the items within it are of the same type and the same size. In fact, the data type is specified by another NumPy object called dtype (data-type); each ndarray is associated with only one type of dtype.

Arrays are similar to lists in Python, except that every element of an array must be of the same type. Items in the collection can be accessed using a zero-based index.

Moreover, another peculiarity of NumPy arrays is that their size is fixed, that is, once you defined their size at the time of creation, it remains unchanged. This behavior is different from Python lists, which can grow or shrink in size.

Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements.

The number of the dimensions and items in an array is defined by its shape, a tuple of N-positive integers that specifies the size for each dimension. The dimensions are defined as **axes** and the number of axes as **rank**.

### Arrays

The central feature of Numpy is the *array* object class. Arrays are similar to lists in Python, except that every element of an array must be of the same type. Items in the collection can be accessed using a zero-based index.

In [4]:
# Syntax 
np.array

<function numpy.array>

In [5]:
x = np.array([1,2,4,5])   # Python assigns the data type creates one- dimensional array
print(x)


[1 2 4 5]


In [6]:
# what is its type? 
print(" type:", type(x))

 type: <class 'numpy.ndarray'>


In [7]:
# What is stored. Type of the item can be checked with the dtype property
print("type of variable:",x.dtype)

type of variable: int64


In [8]:
# how many elements
print("size:", np.size(x))
print("length:", len(x))

size: 4
length: 4


In [9]:
# you can use to force the type
x = np.array([1,2,4,5], float)
print(x)
print("type of x:", x.dtype)

[1. 2. 4. 5.]
type of x: float64


In [10]:
x = np.array([2,1.0,4.0,5.0])   # Python assigns the data type
print(x.dtype)
print(x)

float64
[2. 1. 4. 5.]


In [11]:
x1 = np.array([2,'a',1.0,4.0,5.0])   # Python assigns the data type
print(x1.dtype)
print(x1)

<U32
['2' 'a' '1.0' '4.0' '5.0']


Here, the function array takes two arguments: the list to be converted into the array and the type of each member of the list.

#### ndarray.shape

This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

In [12]:
x1 = (4)
x2 = (4,)
print(" type of x1:", type(x1))
print(" type of x2:", type(x2))

 type of x1: <class 'int'>
 type of x2: <class 'tuple'>


In [13]:
# Shape of the array have one dimension
print(x.shape)

(4,)


In [14]:
print(x.ndim)

1


As there are four elements it prints 4. another way of finding the dimension is use len() function. 


In [15]:
len(x)

4

In [16]:
# repeat a sequence 5 times

print(np.array([2]*5))


[2 2 2 2 2]


### How to create a multidimensional array. 

Two dimensional array are great for representing matrices which are often used in data science.


In [17]:
a = np.array([[10, 20, 30], [40, 50, 60],[70,80,90]])
#a1 = np.array([[10, 20], [40, 50]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [18]:
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3, 3)


In [19]:
a.ndim


2

In [20]:
a.size

9

In [21]:
print(a.dtype)

int64


In [18]:
a1 = np.array([[10, 20, 30], [40, 50, 60]], dtype=float)
print(a1.dtype)
print(a1)

float64
[[10. 20. 30.]
 [40. 50. 60.]]


In [4]:
print('Shape of a1', a1.shape)

Shape of a1 (2, 3)


In [13]:
print(a1[1].shape)

(3,)


In [14]:
print('Size of a1', a1.size)

Size of a1 6


In [15]:
print(len(a1))
print(a1.shape[0])

2
2


In [16]:
a1.shape[0]*a1.shape[1]

6

In [17]:
a1.ndim

2

#### numpy.empty
It creates an uninitialized array of specified shape and dtype.

In [20]:
x =(np.empty([3,3],int))
print(x)

[[ 4607825790175356063 -4611042647052049244  4603322190547985583]
 [-4611042647052049245  4617283349392834113 -4613744806828471525]
 [ 4603322190547985580 -4613744806828471527  4606153024599475607]]


#### Note: 
The elements in an array show random values as they are not initialized


#### numpy.zeros 
Returns a new array of specified size, filled with zeros.

In [24]:
#x = np.zeros(10, dtype  = int)
x = np.zeros(10)
print(x.dtype)
print(x)

float64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [31]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### numpy.ones 
Returns a new array of specified size and type, filled with ones.


In [32]:
x = np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [33]:
x = np.ones([3,3], dtype = int) 
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


we will discuss how to create an array from existing data

#### numpy.asarray

In [34]:
# convert list to ndarray
a = [1,2,3,4]
print(type(a))
#x = np.array(a)
x = np.asarray(a)
print(x)
print(type(x))


<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [35]:
# dtype is set
a = [1,2,3,4]
print(type(a))
x = np.asarray(a, dtype = float)
print(x)
print(type(x))
print(x.dtype)

<class 'list'>
[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float64


In [36]:
# ndarray from tuple 
a = (1,2,3) 
print(type(a))
x = np.asarray(a) 
print(x)
print(type(x))

<class 'tuple'>
[1 2 3]
<class 'numpy.ndarray'>


In [25]:
# ndarray from list of tuples 
a = [(1,2,3),(4,5,6)] 
print(type(a))
print(type(a[0]))
x = np.asarray(a) 
print(x)
print(x.shape)

<class 'list'>
<class 'tuple'>
[[1 2 3]
 [4 5 6]]
(2, 3)


In [46]:
a = np.array([(1,2,3),(4,5,6)])
x = np.asarray(a) 
print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


#### Array from Numerical ranges

we will see how to create an array from numerical ranges


#### numpy. arange

This function returns an ndarray object containing evenly spaced values within a given range. The format of the function is as follows −

numpy.arange(start, stop, step, dtype)

In [39]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


Here default start is zero and step size is one. 

In [40]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# start and stop parameters set 
#import numpy as np 
x = np.arange(1,11,2) 
print(x)

[1 3 5 7 9]


In [42]:
x1 = np.arange(0,11,2)
print(x1)

[ 0  2  4  6  8 10]


#### numpy.linspace
This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified. The usage of this function is as follows −

numpy.linspace(start, stop, num, endpoint, retstep, dtype)

1. start - The starting value of the sequence

2.  stop - The end value of the sequence, included in the sequence if endpoint set to true

3.	num - The number of evenly spaced samples to be generated. Default is 50

4.	endpoint- True by default, hence the stop value is included in the sequence. If false, it is not included

5.	retstep - If true, returns samples and step between the consecutive numbers

6.	dtype - Data type of output ndarray


In [43]:
(20-10)/4  # (stop-start)/(number of points-1)

2.5

In [44]:
x = np.linspace(10,20,5) 
print(x)

[10.  12.5 15.  17.5 20. ]


In [45]:
x1 x2 x3 x4 x5

SyntaxError: invalid syntax (2727051972.py, line 1)

In [ ]:
(20-10)/4

In [28]:
# endpoint set to false 
x = np.linspace(10,20, 5, endpoint = False) 
print(x)

[10. 12. 14. 16. 18.]


In [ ]:
help(np.linspace)

In [ ]:
?np.linspace

In [32]:
# find retstep value 
import numpy as np 

x = np.linspace(1,3,5, endpoint = False) 
print(x) 
# retstep here is 0.5

[1.  1.4 1.8 2.2 2.6]


In [37]:
# This resizes the ndarray
a = np.arange(0,12)
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
m = a.reshape(4,3,order='F')
print(m)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [39]:
m.shape

(4, 3)

In [73]:
np.arange(12).reshape(4,3)
#np.arange(12).reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [74]:
np.arange(12).reshape((4,3),order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [34]:
a1 = np.arange(0,16)
#print(a1.reshape(4,5))
print(a1.reshape(3,3))


ValueError: cannot reshape array of size 16 into shape (3,3)

In [40]:
m

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [41]:
# back to original  
reshape=m.reshape((4,3),order='F')
print(reshape)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [58]:
# The .reshape method is not the only means of reoragnizing data. Another
# means is the .ravel() method that will flatten a matrix into one dimension

raveled = m.ravel()
raveled[0]=1000
print(raveled)
print(m)


# .flatten is like a ravel, but a copy of the data not a view into the source
m2 = np.arange(0,9).reshape(3,3)
flattened = m2.flatten()
flattened[0]= 1000
print(flattened)
print(m2)

[1000    1    2    3    4    5    6    7    8    9   10   11]
[[1000    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]
[1000    1    2    3    4    5    6    7    8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Indexing and slicing
Contents of ndarray object can be accessed and modified by indexing or slicing, just like Python's in-built container objects.

Items in ndarray object follows zero-based index.

Basic slicing is an extension of Python's basic concept of slicing to n dimensions. A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. This slice object is passed to the array to extract a part of array.

In [43]:
a = np.arange(0,20,2) 
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
a[2]

4

In [45]:
a[[1,3,6]]

array([ 2,  6, 12])

In [46]:
s = np.arange(2,10,3) 
s

array([2, 5, 8])

In [47]:
print(a[s])   ## a[[2,5,8]]

[ 4 10 16]


In [48]:
print(a[[2,5,8]])

[ 4 10 16]


In [49]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In the above example, an ndarray object is prepared by arange() function. Then a slice object is defined with start, stop, and step values 2, 10, and 2 respectively. When this slice object is passed to the ndarray, a part of it starting with index 2 up to 10 with a step of 2 is sliced.

The same result can also be obtained by giving the slicing parameters separated by a colon : (start:stop:step) directly to the ndarray object.

In [50]:
x = a[2:10:2]  #{2,4,6,8}
print(x)

[ 4  8 12 16]


If only one parameter is put, a single item corresponding to the index 
will be returned. If a : is inserted in front of it, all items from that index onwards will be extracted. If two parameters (with : between them) is used, items between the two indexes (not including the stop index) with default step one are sliced.

In [51]:
a = np.arange(10) 
b = a[3] 
print (b)

3


In [52]:
# slice items starting from index 
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [53]:
print(a[3:])

[3 4 5 6 7 8 9]


In [54]:
# slice items between indexes 
a = np.arange(10) 
print(a[:7])

[0 1 2 3 4 5 6]


The above description applies to multi-dimensional ndarray too

In [55]:
x = np.array([[10,20,30],[40,50,60],[70,80,90]]) 
print(x) 
print("shape of x:",x.shape)
print("Total elements in x:", x.size)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
shape of x: (3, 3)
Total elements in x: 9


In [56]:
#x[1,2] 
x[1][2]

60

In [57]:
x.shape

(3, 3)

In [58]:
x.shape[0]   # Gives the rows

3

In [59]:
x[1]

array([40, 50, 60])

In [88]:
# slice items starting from index
print('Now we will slice the array from the index a[1:] \n' )
print(x[1:])

Now we will slice the array from the index a[1:] 

[[40 50 60]
 [70 80 90]]


Slicing can also include ellipsis (…) to make a selection tuple of the same length as the dimension of an array. If ellipsis is used at the row position, it will return an ndarray comprising of items in rows.

In [125]:
x = np.array([[10,20,30],[40,50,60],[70,80,90]]) 

print ('Our array is:') 
print(x)
print ('\n')  

Our array is:
[[10 20 30]
 [40 50 60]
 [70 80 90]]




In [126]:
# this returns array of items in the second column 
print ('The items in the second column are:')  
print (x[...,1]) 
print ('\n')  

The items in the second column are:
[20 50 80]




In [127]:
# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (x[1,...]) 
print ('\n')  

The items in the second row are:
[40 50 60]




In [128]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [129]:
# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (x[...,1:])

The items column 1 onwards are:
[[20 30]
 [50 60]
 [80 90]]


In [130]:
x1 = np.array([[1,2,3,6], [4,5,6,7], [7,8,9,8],[10,11,12,13]])
x1

array([[ 1,  2,  3,  6],
       [ 4,  5,  6,  7],
       [ 7,  8,  9,  8],
       [10, 11, 12, 13]])

In [131]:
x1[2:,...]

array([[ 7,  8,  9,  8],
       [10, 11, 12, 13]])

In [132]:
x1[1:3,...]

array([[4, 5, 6, 7],
       [7, 8, 9, 8]])

In [133]:
x1

array([[ 1,  2,  3,  6],
       [ 4,  5,  6,  7],
       [ 7,  8,  9,  8],
       [10, 11, 12, 13]])

In [134]:
print (x1[:,1:])

[[ 2  3  6]
 [ 5  6  7]
 [ 8  9  8]
 [11 12 13]]


In [135]:
x1[[0,2,3],[0,2,1]]

array([ 1,  9, 11])

In [136]:
x1[[3,3],[1,2]]
#x1[[3,3,4],[1,2,4]]

array([11, 12])

In [137]:
# this returns array of items in the second column 
print ('The items in the second column are:')  
print (x1[:,1]) 
print ('\n')  
x1[[0,2,3],[0,2,1]]
# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (x1[1,:]) 
print ('\n')  

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (x1[:,1:])

The items in the second column are:
[ 2  5  8 11]


The items in the second row are:
[4 5 6 7]


The items column 1 onwards are:
[[ 2  3  6]
 [ 5  6  7]
 [ 8  9  8]
 [11 12 13]]


In [138]:
x1

array([[ 1,  2,  3,  6],
       [ 4,  5,  6,  7],
       [ 7,  8,  9,  8],
       [10, 11, 12, 13]])

In [139]:
x1

array([[ 1,  2,  3,  6],
       [ 4,  5,  6,  7],
       [ 7,  8,  9,  8],
       [10, 11, 12, 13]])

#### Boolean Array Indexing
In this example, items greatre than 50 are returned


In [140]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [141]:
x2= x>50
x2

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [143]:
# Now we will print the items greater than 50 
print ('The items greater than 50 are:' )
xg50=x[x > 50]
print(xg50)

The items greater than 50 are:
[60 70 80 90]


In [144]:
xg50.sum()

300

In [146]:
print(x[(x>50)].sum())
print(x)

300
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [147]:
x.size

9

In [148]:
x1

array([[ 1,  2,  3,  6],
       [ 4,  5,  6,  7],
       [ 7,  8,  9,  8],
       [10, 11, 12, 13]])

In [149]:
x2 = x1[x1>50]
print(x2)
print((x2.size))

[]
0


In [152]:
#x1[x1>50]
print(x[x>50].all())


True


In [154]:
print((x>50).sum())

4


In [155]:
x = [2,3,4]
counter1 = 0
for i in x:
    print(i)
    if(i > 2):
        counter1 = counter1+1
        #print(i)

print(counter1)
        

2
3
4
2


In [156]:
x = np.array([2,3,4])
(x>2).sum()

2

In [157]:
# In this example, NaN elements are omitted using ~
x = np.array([np.nan, 10,20,np.nan,30,40,50])
print(x)

[nan 10. 20. nan 30. 40. 50.]


In [158]:
np.isnan(x)

array([ True, False, False,  True, False, False, False])

In [159]:
~np.isnan(x)

array([False,  True,  True, False,  True,  True,  True])

In [161]:
print(x[~np.isnan(x)])

[10. 20. 30. 40. 50.]


#### Broadcasting

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

In [162]:
x1 = np.array([10,20,30,40]) 
x2 = np.array([10,20,30,40]) 
x = x1 * x2 
print(x)

[ 100  400  900 1600]


If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes.


In [163]:
x1 = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
x2 = np.array([1.0,2.0,3.0])  
   
print ('First array:') 
print (x1) 
print ('\n')  
   
print ('Second array:') 
print (x2) 
print ('\n')  
   
print ('First Array + Second Array') 
print(x1+x2)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


#### Iterating over array 

NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

Let us create a 3X4 array using arange() function and iterate over it using nditer.

In [164]:
x = np.arange(0,60,5)
x = x.reshape(3,4)

print ('Original array is:')
print (x)
print ('\n')

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]




In [165]:
print ('Modified array is:')
for i in np.nditer(x):
    #print (i)
    print(i, end = ' ')

Modified array is:
0 5 10 15 20 25 30 35 40 45 50 55 

In [104]:
for i in np.nditer(x, order = "F"):
   print (i, end = ' ')

0 20 40 5 25 45 10 30 50 15 35 55 

#### Array Manipulation
Several routines are available in numpy package for manipulation of elements in
ndarray object. we will discuss few of them 

numpy.reshape

In [105]:
x = np.arange(12)
print ('The original array:')
print (x)
print ('\n')

x1 = x.reshape(4,3)
print ('The modified array:')
print (x1)

The original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]


The modified array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [106]:
x = np.arange(12).reshape(3,4) 
print ('The original array:') 
print (x) 
print ('\n') 


The original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]




In [110]:
x = np.arange(12).reshape(12,-1) 
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

#### Transpose Operations

numpy.transpose


In [111]:
x = np.arange(12).reshape(3,4)

print ('The original array is:') 
print (x)   

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [112]:
print ('The transposed array is:') 
print (np.transpose(x))

The transposed array is:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [113]:
print('Alternatively, this can also be performed with the .T property:')
print(x.T)

Alternatively, this can also be performed with the .T property:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


#### Joining Arrays

numpy.concatenate


Concatenation refers to joining. This function is used to join two or more arrays of the same shape along a specified axis.

In [114]:
a = np.array([[1,2],[3,4]]) 

print ('First array:') 
print (a) 
print('dim of a: ', a.shape)
print ('\n')  
b = (np.array([[5,6],[7,8]])) 
print ('Second array:') 
print (b) 
print('dim of b: ', b.shape)
print ('\n')  
# both the arrays are of same dimensions

First array:
[[1 2]
 [3 4]]
dim of a:  (2, 2)


Second array:
[[5 6]
 [7 8]]
dim of b:  (2, 2)




In [115]:
y = np.array([[1,2],[3,4],[5,6],[7,8]])
print(y)   ## This is known as vertical concatenation

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [116]:
y = np.array([[1,2,5,6],[3,4,7,8]])
print(y)  ### This is known a horizontal concatenation

[[1 2 5 6]
 [3 4 7 8]]


In [117]:
print ('Joining the two arrays along axis 0:') 
print (np.concatenate((a,b))) 
print ('\n')  

Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]




In [118]:
print ('Joining the two arrays along axis 1:') 
print (np.concatenate((a,b),axis = 1))

Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [119]:
# numpy.hstack

import numpy as np 
a = np.array([[1,2],[3,4]]) 

print ('First array:') 
print (a) 
print ('\n')  
b = np.array([[5,6],[7,8]]) 

print ('Second array:') 
print (b) 
print ('\n')  

print ('Horizontal stacking:') 
c = np.hstack((a,b)) 
print (c) 
print ('\n')
print(c.shape)

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Horizontal stacking:
[[1 2 5 6]
 [3 4 7 8]]


(2, 4)


In [120]:
# numpy.vstack

import numpy as np 
a = np.array([[1,2],[3,4]]) 

print ('First array:') 
print (a) 
print ('\n')  
b = np.array([[5,6],[7,8]]) 

print ('Second array:') 
print (b) 
print ('\n')  

print ('vertical stacking:') 
c = np.vstack((a,b)) 
print (c) 
print ('\n')
print(c.shape)

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


vertical stacking:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


(4, 2)


numpy.split

This function divides the array into subarrays along a specified axis.



In [121]:
a = np.arange(9) 

print ('First array:') 
print (a) 
print ('\n')  

print ('Split the array in 3 equal-sized subarrays:' )
b = np.split(a,3) 
print (b) 
print ('\n')
print(type(b))

First array:
[0 1 2 3 4 5 6 7 8]


Split the array in 3 equal-sized subarrays:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


<class 'list'>


In [122]:
print ('Split the array at positions indicated in 1-D array:' )
b = np.split(a,[3,7])
print (b) 

Split the array at positions indicated in 1-D array:
[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8])]


numpy.hsplit

The numpy.hsplit is a special case of split() function where axis is 1 indicating a horizontal split regardless of the dimension of the input array.

In [166]:
a = np.arange(16).reshape(4,4) 

print ('First array:' )
print (a) 
print ('\n')  

print ('Horizontal splitting:') 
b = np.hsplit(a,2) 
print (b) 
print ('\n')

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Horizontal splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]




numpy.vsplit

The numpy.vsplit is a special case of split() function where axis is 1 indicating a horizontal split regardless of the dimension of the input array.

In [167]:
a = np.arange(16).reshape(4,4) 

print ('First array:' )
print (a) 
print ('\n')  

print ('Horizontal splitting:') 
b = np.vsplit(a,2) 
print (b) 
print ('\n')

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Horizontal splitting:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]




numpy.resize

This function returns a new array with the specified size. If the new size is greater than the original, the repeated copies of entries in the original are contained.

In [ ]:
a = np.array([[1,2,3],[4,5,6]]) 

print ('First array:') 
print (a) 
print ('\n')

print ('The shape of first array:' )
print (a.shape) 
print ('\n')  
b = np.resize(a, (3,2)) 

print ('Second array:') 
print (b) 
print ('\n')  

print ('The shape of second array:') 
print (b.shape) 
print ('\n')

# Observe that first row of a is repeated in b since size is bigger 

print ('Resize the second array:' )
b = np.resize(a,(3,3)) 
print (b)

numpy.insert 

This function inserts values in the input array along the given axis and before the given index. If the type of values is converted to be inserted, it is different from the input array. 

Also, if the axis is not mentioned, the input array is flattened.

In [168]:
import numpy as np 
a = np.array([[1,2],[3,4],[5,6]]) 

print ('First array:') 
print (a) 
print ('\n')  

First array:
[[1 2]
 [3 4]
 [5 6]]




In [169]:
print ('Axis parameter not passed. The input array is flattened before insertion.')
print (np.insert(a,3,[11,12])) 
print ('\n')  
print ('Axis parameter passed. The values array is broadcast to match input array.')

Axis parameter not passed. The input array is flattened before insertion.
[ 1  2  3 11 12  4  5  6]


Axis parameter passed. The values array is broadcast to match input array.


In [170]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [171]:
print ('Broadcast along axis 0:') 
print (np.insert(a,1,[11,12],axis = 0)) 
print ('\n')  

Broadcast along axis 0:
[[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]




In [172]:
print ('Broadcast along axis 1:' )
print (np.insert(a,2,[11,12,13],axis = 1))

Broadcast along axis 1:
[[ 1  2 11]
 [ 3  4 12]
 [ 5  6 13]]


numpy.delete

This function returns a new array with the specified subarray deleted from the input array. It behaves almost same way as numpy.insert


In [173]:
np.arange(0,18,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [174]:
a = np.arange(0,18,2).reshape(3,3) 

print ('First array:') 
print (a)   

First array:
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [ ]:
[0 2 4 6 8 10 12 14 16]

In [175]:
print ('Array flattened before delete operation as axis not used:' )
print (np.delete(a,7)) 
print ('\n')  

Array flattened before delete operation as axis not used:
[ 0  2  4  6  8 10 12 16]




In [176]:
a

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [177]:
print ('Column 2 deleted:')  
print (np.delete(a,2,axis = 1)) 
print ('\n')  

Column 2 deleted:
[[ 0  2]
 [ 6  8]
 [12 14]]




In [178]:
print ('row 2 deleted:')  
print (np.delete(a,1,axis = 0)) 
print ('\n') 

row 2 deleted:
[[ 0  2  4]
 [12 14 16]]




In [186]:
print ('A slice containing alternate values from array deleted:') 
a = np.array([1,2,3,4,5,6,7,8,9,10]) 
print (np.delete(a, np.s_[::2]))

A slice containing alternate values from array deleted:
[ 2  4  6  8 10]


Lists can also be created from arrays:

In [187]:
a = np.array([1, 2, 3], float)
a1=a.tolist()
print(type(a1))

print(a1)


<class 'list'>
[1.0, 2.0, 3.0]


One can fill an array with a single value

In [188]:
a = np.array([1, 2, 3], float)
print("original array",a)
a.fill(0)
print("modified after filing zeros", a)

original array [1. 2. 3.]
modified after filing zeros [0. 0. 0.]


In [189]:
# create a 2x2 array filled with 10.0
x1 = np.full((2,2), 10.0)
print(x1)

[[10. 10.]
 [10. 10.]]


In [190]:
# create a 4x4 matrix with the diagonal 1s and the others 0s
x = np.eye(4,4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [191]:
x1= np.identity(4)
print(x1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


The *eye* function returns matrix with ones along the kth diagonal:

In [194]:
 np.eye(3, k=2, dtype=float)  # upper diagonal

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [195]:
np.eye(3, k=-2, dtype=float)  # lower diagonal

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

## Array Operations/Mathematics
When standard mathematical operations are used with arrays, they are applied on an element- by-element basis. This means that the arrays should be the same size during addition, subtraction, etc.:

In [196]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
print(a)
print(b)

[1. 2. 3.]
[5. 2. 6.]


In [197]:
print(a + b)

[6. 4. 9.]


In [198]:
np.add(a,b)

array([6., 4., 9.])

In [199]:
print(a-b)

print(np.subtract(a,b))

[-4.  0. -3.]
[-4.  0. -3.]


In [200]:
print(a*b)

print(np.multiply(a,b))

[ 5.  4. 18.]
[ 5.  4. 18.]


In [201]:
print(a/b)

np.divide(a,b)

[0.2 1.  0.5]


array([0.2, 1. , 0.5])

For two-dimensional arrays, multiplication remains elementwise and does not correspond to matrix multiplication. There are special functions for matrix math that we will cover later.

In [202]:
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)
print("a:",a)
print("\n")
print("b:",b)

a: [[1. 2.]
 [3. 4.]]


b: [[2. 0.]
 [1. 3.]]


In [203]:
a * b

array([[ 2.,  0.],
       [ 3., 12.]])

In [204]:
 a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
print(a)
print('\n')
print(b)
print('\n')
print(a + b)
print('\n')
print(np.add(a,b))   ## we can use add funtion from numpy

[[1. 2.]
 [3. 4.]
 [5. 6.]]


[-1.  3.]


[[0. 5.]
 [2. 7.]
 [4. 9.]]


[[0. 5.]
 [2. 7.]
 [4. 9.]]


In addition to the standard operators, NumPy offers a large library of common mathematical functions that can be applied elementwise to arrays. Among these are the functions: *abs, sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh,and arctanh*. The functions *floor, ceil, and rint* give the lower, upper, or nearest (rounded) integer:

In [205]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [206]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [207]:
np.floor(np.sqrt(a))

array([[1., 1.],
       [1., 2.],
       [2., 2.]])

In [208]:
np.ceil(np.sqrt(a))

array([[1., 2.],
       [2., 2.],
       [3., 3.]])

In [209]:
np.round(np.sqrt(a), 2)

array([[1.  , 1.41],
       [1.73, 2.  ],
       [2.24, 2.45]])

Also included in the NumPy module are two important mathematical constants: pi and exponent


In [210]:
np.pi

3.141592653589793

In [211]:
np.e

2.718281828459045

In [212]:
print(np.exp(a))

[[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]
 [148.4131591  403.42879349]]


### Basic Array operations

Many functions exist for extracting whole-array properties. The items in an array can be summed or multiplied:

In [ ]:
a = np.array([2, 4, 3], float)
print("sum of elements:", a.sum())

print(" another way:")
print("product of elements:", np.sum(a))

In [ ]:
a = np.array([2, 4, 3], float)
print("product of elements:", a.prod())

print(" another way:")
print("product of elements:", np.prod(a))

In [ ]:
print(a.mean())

print(" another way:")
print("mean:", np.mean(a))

In [ ]:
print(a.min())

print(" another way:")
print("mean:", np.min(a))  

For multidimensional arrays, each of the functions thus far described can take an optional argument axis that will perform an operation along only the specified axis, placing the results in a return array:

In [ ]:
a = np.array([[0, 2], [3, -1], [3, 5]])
print(a)

In [ ]:
a.min()

In [ ]:
print(a.min(axis = 0))   # 0 for column

print(" another way:")
print("min:", np.min(a, axis = 0))

In [ ]:
print(a.min(axis = 1))   # 1 for row

print(" another way:")
print("min:", np.min(a, axis = 1))

#### numpy.amin() and numpy.amax()

These functions return the minimum and the maximum from the elements in the given array along the specified axis.


In [ ]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print ('array is:') 
print (a)  
print ('\n')  

In [ ]:
print ('Applying amin() function:') 
print (np.amin(a,1)) 
print ('\n')  

In [ ]:
print ('Applying amin() function again:') 
print (np.amin(a,0)) 
print ('\n')  

In [ ]:
print ('Applying amax() function:') 
print (np.amax(a)) 
print ('\n')  

print ('Applying amax() function again:') 
print (np.amax(a, axis = 0))

In [ ]:
#### numpy.percentil()


a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

print ('Given array is:') 
print (a) 
print ('\n')  

print ('Applying percentile() function:') 
print (np.percentile(a,50)) 
print ('\n')  

print ('Applying percentile() function along axis 1:') 
print (np.percentile(a,50, axis = 1) )
print ('\n')  

print ('Applying percentile() function along axis 0:') 
print (np.percentile(a,50, axis = 0))

In [ ]:
print(a.mean())

In [ ]:
print(a.mean(axis = 1))   # 1 for row

print(" another way:")
print("mean:", np.mean(a, axis = 1))

#### numpy.power()

This function treats elements in the first input array as base and returns it raised to the power of the corresponding element in the second input array

In [ ]:
a = np.array([10,100,1000]) 

print ('Our array is:') 
print (a) 
print ('\n')  

print ('Applying power function:') 
print (np.power(a,2)) 
print ('\n')  

print ('Second array:') 
b = (np.array([1,2,3])) 
print (b) 
print ('\n')  

print ('Applying power function again:') 
print (np.power(a,b))

In addition to the mean, var, and std functions, Numpy supplies several other methods for returning statistical features of arrays. The correlation coefficient for multiple variables observed at multiple instances can be found for arrays of the form [[x1, x2, ...], [y1, y2, ...], [z1, z2, ...], ...] where x, y, z are different observables and the numbers indicate the observation times:


In [ ]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8],[6,7,8,9]])
print(a)
print('\n')
c = np.corrcoef(a)
print(c)

In [ ]:
a = np.array([6, 2, 5, -1, 0])
sorted(a)
a.sort()
a


For two dimensional arrays, the diagonal can be extracted:

In [ ]:
a = np.array([[1, 2], [3, 4]], float)

print(a)
#a.diagonal()

print(np.diagonal(a))

## Dot Product on Matrices and Inner Product on Vectors:

In [ ]:
# determine the dot product of two matrices
x2d = np.array([[1,2],[2,3]])
y2d = np.array([[3,2],[4,5]])

print(x2d)
print("\n")

print(y2d)

In [ ]:
print(x2d.dot(y2d))

print(np.dot(x2d, y2d))

In [ ]:
# determine the inner product of two vectors
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

It is also possible to generate inner, outer, and cross products of matrices and vectors. For vectors, note that the inner product is equivalent to the dot product:

In [ ]:
x1 = np.array([1, 4, 0])
y1 = np.array([2, 2, 1])

In [ ]:
np.outer(x1,y1)

In [ ]:
np.inner(x1,y1)

In [ ]:
np.cross(x1,y1)

NumPy also comes with a number of built-in routines for linear algebra calculations. These can be found in the sub-module linalg. Among these are routines for dealing with matrices and their inverses. The determinant of a matrix can be found:

In [ ]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]])

np.linalg.det(a)

In [ ]:
# inverse of a matrix
b = np.linalg.inv(a)
print(b)

In [ ]:
#(np.dot(a,b))
np.round((np.dot(a,b)))

In [ ]:
# numpy determinant
a = np.array([[1,2], [3,4]]) 
print (np.linalg.det(a))

In [ ]:
# numpy.linalg.inv()

x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print (x) 
print (y) 
print (np.dot(x,y))

One can find the eigenvalues and eigenvectors of a matrix

In [ ]:
vals, vecs = np.linalg.eig(a)
print("eigen value:", "\n")
print(vals)
print("eigen vectrs:", "\n")
print(vecs)


Singular value decomposition (analogous to diagonalization of a nonsquare matrix) can also be performed:

In [ ]:
a = np.array([[1, 3, 4], [5, 2, 3]], float)
U, s, Vh = np.linalg.svd(a)
print(U, "\n")
print(s, "\n")
print(Vh, "\n")


## Set Operations:


In [ ]:
x1 = np.array(['John','Stacy','Ron'])
x2 = np.array(['Don','Mat','Ron'])
print(x1, x2)

In [ ]:
print( np.intersect1d(x1,x2))

In [ ]:
print( np.union1d(x1,x2))

In [ ]:
print( np.setdiff1d(x1,x2)) # elements in x1 and not in x2

In [ ]:
print( np.in1d(x1,x2))   # elements in x1 in x2

 It is possible to test whether or not values  are NAN ("not a number") or finite

In [ ]:
a = np.array([1, np.NaN, np.Inf])
a

In [ ]:
np.isnan(a)

In [ ]:
np.isfinite(a)

There are various logical operations also.

In [ ]:
a = np.array([[6, 4], [5, 9]])

In [ ]:
a>=5

In [ ]:
a[a>=5]  # Returs the elements greater or equal to 5

In [ ]:
# another way
indx = (a>=5)

a[indx]

In [ ]:
# Logical and operation

a[np.logical_and(a>5, a<9)]

For multidimensional arrays, we have to send multiple one-dimensional integer arrays to the selection bracket, one for each axis. Then, each of these selection arrays is traversed in sequence: the first element taken has a first axis index taken from the first member of the first selection array, a second index from the first member of the second selection array, and so on.

In [ ]:
a = np.array([[1, 4], [9, 16]], float)
print(a)

In [ ]:
indx_row = np.array([0, 0, 1, 1, 0,1], int)
indx_col = np.array([0, 1, 1, 1, 1,0], int)
a[indx_row, indx_col]

However, arrays that do not match in the number of dimensions will be 
broadcasted by Python to perform mathematical operations. 
This often means that the smaller array will be repeated as necessary 
to perform the operation indicated. Consider the following:

Errors are thrown if arrays do not match in size:

In [ ]:
a = np.array([1,2,3], float)
b = np.array([4,5], float)
b+a

### Random Numbers
An important part of any simulation is the ability to draw random numbers. For this purpose, we use NumPy's built-in pseudorandom number generator routines in the sub-module random. The numbers are pseudo random in the sense that they are generated deterministically from a seed number, but are distributed in what has statistical similarities to random fashion. NumPy uses a particular algorithm called the Mersenne Twister to generate pseudorandom numbers.
The random number seed can be set:

In [ ]:
np.random.seed(1234)

The seed is an integer value. Any program that starts with the same seed will generate exactly the same sequence of random numbers each time it is run. This can be useful for debugging purposes, but one does not need to specify the seed and in fact, when we perform multiple runs of the same simulation to be averaged together, we want each such trial to have a different sequence of random numbers. If this command is not run, NumPy automatically selects a random seed (based on the time) that is different every time a program is run.
An array of random numbers in the half-open interval [0.0, 1.0) can be generated:

In [ ]:
# Create an array of random numbers between 0 and 1
np.random.seed(1234)
x1 = np.random.random(3)
print(x1, "\n")

In [ ]:
x3= np.random.random((2,2))
print(x3)

In [ ]:
# Create an array of random integers between 1 and 20
x3= np.random.randint(1,20, 11)
print(x3)

In [ ]:
# To draw from a continuous normal distribution with mean = 1 and std = 10 
# and 20 points
x3= np.random.normal(1, 10, 100000)
print(np.mean(x3))
print(np.std(x3))

# To draw from a continuous normal distribution with mean = 0 and std = 1 
# and 20 points
x4= np.random.normal(size = 20)

In [ ]:
# Function for rounding
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 

print ('Original array:') 
print (a) 
print ('\n')  

print ('After rounding:') 
print (np.around(a)) 
print (np.around(a, decimals = 1)) 

In [ ]:
# numpy.floor()


a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 

print ('The given array:') 
print (a) 
print ('\n')  

print ('The modified array:') 
print (np.floor(a))

In [ ]:
# numpy.ceil()


a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 

print ('The given array:') 
print (a) 
print ('\n')  

print ('The modified array:') 
print (np.ceil(a))

#### I/O with numpy

The ndarray objects can be saved to and loaded from the disk files. The IO functions available are −

load() and save() functions handle /numPy binary files (with npy extension)

loadtxt() and savetxt() functions handle normal text files

This .npy file stores data, shape, dtype and other information required to reconstruct the ndarray in a disk file such that the array is correctly retrieved even if the file is on another machine with different architecture.

numpy.save() stores teh input array file with .npy extension

To reconstruct array from outfile.npy, use load() function.

In [ ]:
x = np.array([10,20,30,40,50]) 
np.save('out_x',x)

In [ ]:
data = np.load('out_x.npy') 
print(data)

In [ ]:
x = np.array([1,2,3,4,5]) 
np.savetxt('out.txt',x) 
y = np.loadtxt('out.txt') 
print (x)

In [ ]:
# Reading a .csv file

#It's possible to use NumPy to directly read csv or other files into arrays. 
#We can do this using the 
#numpy.genfromtxt function.
#NumPy will automatically pick a data type for the elements in an array 
#based on their format.


df = np.genfromtxt("coursera_logistic_data.csv", delimiter=",", skip_header=1)
df
type(df)
df.shape

NumPy contains many other built-in functions that we have not covered here. In particular, there are routines for discrete Fourier transforms, more complex linear algebra operations, size / shape / type testing of arrays, splitting and joining arrays, histograms, creating arrays of numbers spaced in various ways, creating and evaluating functions on grid arrays, treating arrays with special (NaN, Inf) values, set operations, creating various kinds of special matrices, and evaluating special mathematical functions (e.g., Bessel functions). You are encouraged to consult the NumPy documentation at http://docs.scipy.org/doc/ for more details.